defaults:
  - defaults
  - _self_

device: cuda

run_dir: ???
protocol: #  (is all 4), normal (a), threshold (b), nsim (c), guo (d)
  - normal
  - guo

threshold: 0.95 # threashold to compute (b)
samples_path: null
dataset: 'sinc_synth' # motionfix

ckpt: last
batch_size: 256
