defaults:
  - defaults
  - _self_

device: cuda

run_dir: outputs/tmr_humanml3d_amass_feats
protocol: #  (is all 4), normal (a), threshold (b), nsim (c), guo (d)
  - normal
  - guo

threshold: 0.95 # threashold to compute (b)
samples_path: null
dataset: 'hml_3d' # motionfix

ckpt: last
batch_size: 256
